// Product Database
const productsData = {
  "immersion-suit": {
    id: "immersion-suit",
    name: "Immersion Suit",
    category: "Life-Saving Equipment",
    certified: true,
    certificationText: "IMO & SOLAS Certified",
    description:
      "High-performance immersion suit designed to protect crew members in cold water emergencies. Maintains body core temperature and provides buoyancy in extreme conditions. Suitable for adult universal sizing with superior thermal protection.",
    images: [
      "src/assets/1.png",
      // "src/assets/2.png",
      // "src/assets/3.png",
      // "src/assets/4.png",
    ],
    specifications: [
      { label: "Type", value: "Adult Universal" },
      { label: "Weight", value: "4.5 kg" },
      { label: "Buoyancy", value: "More than 142N" },
      { label: "Water Permeability", value: "Less than 200g after 1 hour" },
      { label: "Package Size", value: "640×330×210mm" },
      { label: "Outer Fabric", value: "CR (Chloroprene Rubber)" },
    ],
    features: [
      "Body core temperature doesn't fall more than 2°C in 0-2°C water",
      "Buoyancy decrease less than 5% after 24 hours submersion",
      "Superior thermal protection in cold water",
      "Universal adult sizing for quick deployment",
      "High-visibility color for easy rescue identification",
      "Durable CR outer fabric construction",
    ],
    compliance: [
      "IMO Res. MSC.81(70) as amended",
      "SOLAS 74 Reg.III/7, III/22, III/32, III/34 as amended",
      "IMO Res. MSC.36(63)",
      "IMO Res. MSC.48(66)",
      "IMO Res. MSC.97(73)",
      "MSC 207(81)",
      "MSC 323(89)",
    ],
  },
  liferaft: {
    id: "liferaft",
    name: "Liferaft",
    category: "Life-Saving Equipment",
    certified: true,
    certificationText: "SOLAS Approved Equipment",
    description:
      "Premium quality inflatable liferaft with SOLAS A Pack equipment outfit. Available in various capacities from 6 to 25 persons. Designed for maximum storage height of 18-50m with comprehensive emergency provisions and survival equipment.",
    images: [
      "src/assets/2.png",
      "src/assets/2.0.png",
      // "src/assets/3.png",
      // "src/assets/4.png",
    ],
    specifications: [
      { label: "Type Series", value: "HLX-6, 8, 10, 12, 15, 16, 20, 25" },
      { label: "Capacity Range", value: "6 to 25 Persons" },
      { label: "Max Storage Height", value: "18-50 meters" },
      { label: "Equipment Outfit", value: "SOLAS A Pack" },
      { label: "Container Type", value: "Fiberglass/GRP Container" },
      { label: "Certification", value: "SOLAS Approved" },
    ],
    features: [
      "Available in multiple capacities (6, 8, 10, 12, 15, 16, 20, 25 persons)",
      "SOLAS A Pack complete equipment outfit",
      "High-quality inflatable construction",
      "Suitable for storage heights up to 50 meters",
      "Comprehensive survival equipment included",
      "Regular inspection and servicing available",
      "Durable fiberglass container protection",
    ],
    compliance: [
      "SOLAS 74 Convention as amended",
      "IMO Res. MSC.81(70)",
      "ISO 9650-1:2005",
      "Reg. III/11, Reg. III/34 of SOLAS",
      "Res. MSC.36(63)-1994 HSC Code",
      "Res. MSC.48(66) - LSA Code",
      "MSC.1/Circ.1285",
    ],
  },
  "embarkation-ladder": {
    id: "embarkation-ladder",
    name: "Embarkation Ladder",
    category: "Deck & Safety Equipment",
    certified: true,
    certificationText: "IMO & ISO Certified",
    description:
      "Heavy-duty embarkation ladder constructed with imported hardwood steps and aluminum alloy frames. Designed for safe embarkation and disembarkation from vessels. Features flat board design with 32mm orifice for secure attachment.",
    images: [
      "src/assets/3.png",
      // "src/assets/1.png",
      // "src/assets/2.png",
      // "src/assets/4.png",
    ],
    specifications: [
      { label: "Board Type", value: "Flat Board (Long/Short)" },
      { label: "Short Board Size", value: "525×115×28mm" },
      { label: "Long Board Size", value: "1800×115×28mm" },
      { label: "Orifice Diameter", value: "32mm" },
      { label: "Wood Material", value: "Imported Hardwood (Liu An)" },
      { label: "Frame Material", value: "Aluminum Alloy" },
    ],
    features: [
      "Heavy-duty construction for reliable performance",
      "Imported hardwood steps for durability",
      "Aluminum alloy frame for lightweight strength",
      "Flat board design for stable footing",
      "32mm orifice for secure rope attachment",
      "Compliant with IMO and ISO standards",
      "Available in customizable lengths",
    ],
    compliance: [
      "IMO Res. A.1045(27)",
      "ISO 799:2004",
      "SOLAS 74 Reg. V/23 as amended",
      "IMO MSC Circ.1428",
      "ISO 5489:2008(E)",
    ],
  },
  "pilot-ladder": {
    id: "pilot-ladder",
    name: "Pilot Ladder",
    category: "Deck & Safety Equipment",
    certified: true,
    certificationText: "IMO & ISO Certified",
    description:
      "Professional-grade pilot ladder manufactured to meet international maritime standards. Features imported hardwood steps with anti-slip grooves and durable construction for safe pilot boarding operations in all weather conditions.",
    images: [
      "src/assets/4.png",
      // "src/assets/1.png",
      // "src/assets/2.png",
      // "src/assets/3.png",
    ],
    specifications: [
      { label: "Board Size", value: "525×115×28mm" },
      { label: "Wood Material", value: "Imported Hardwood (Liu An)" },
      { label: "Orifice Diameter", value: "32mm" },
      { label: "Length Options", value: "Customizable" },
      { label: "Step Design", value: "Anti-slip grooves" },
      { label: "Certification", value: "IMO Res. A.1045(27)" },
    ],
    features: [
      "Anti-slip groove design for enhanced safety",
      "Imported hardwood construction for durability",
      "Meets all international pilot ladder standards",
      "Regular step spacing for easy climbing",
      "Weather-resistant materials",
      "Available in custom lengths",
      "Heavy-duty side ropes for reliability",
    ],
    compliance: [
      "IMO Res. A.1045(27)",
      "ISO 799:2004",
      "SOLAS 74 Reg. V/23 as amended",
      "IMO MSC Circ.1428",
      "ISO 5489:2008(E)",
    ],
  },
  "life-jacket": {
    id: "life-jacket",
    name: "Life Jacket",
    category: "Life-Saving Equipment",
    certified: true,
    certificationText: "SOLAS & MED Approved",
    description:
      "High-quality adult life jacket with 149N buoyancy. Features EPE foam construction with polyester outer fabric for maximum comfort and safety. Designed for users weighing 43-140 kg and height 155 cm or more.",
    images: [
      "src/assets/5.png",
      "src/assets/5.0.png",
      "src/assets/5.1.png",
      // "src/assets/3.png",
    ],
    specifications: [
      { label: "Type", value: "Adult" },
      { label: "Buoyancy", value: "149 N" },
      { label: "Weight", value: "0.7 kg" },
      { label: "Outer Fabric", value: "Polyester" },
      { label: "Floating Material", value: "EPE Foam" },
      { label: "Package Size", value: "580×340×120mm" },
      { label: "User Weight Range", value: "43-140 kg" },
      { label: "User Height", value: "155 cm or more" },
    ],
    features: [
      "149N buoyancy for reliable flotation",
      "Lightweight design at only 0.7 kg",
      "Comfortable EPE foam construction",
      "Durable polyester outer fabric",
      "High-visibility color for easy spotting",
      "Suitable for wide range of body sizes",
      "SOLAS and MED approved",
      "Whistle and reflective tape included",
    ],
    compliance: [
      "MSC.47(66)-1996 Amendments",
      "SOLAS 1974 as amended",
      "MSC.200(81)",
      "MSC.81(70)",
      "MSC.200(80)",
      "MSC.323(89)",
      "MSC.207(81)",
      "MSC.218(82) LSA Code",
    ],
  },
  eebd: {
    id: "eebd",
    name: "EEBD",
    category: "Fire Safety Equipment",
    certified: true,
    certificationText: "SOLAS Approved Equipment",
    description:
      "Compact emergency escape breathing device designed for quick evacuation from hazardous atmospheres. Features 3L alloy steel cylinder providing 15 minutes of breathing time. Includes protective hood and pressure gauge for safe escape operations.",
    images: [
      "src/assets/6.png",
      // "src/assets/1.png",
      // "src/assets/2.png",
      // "src/assets/3.png",
    ],
    specifications: [
      { label: "Cylinder Volume", value: "3 Liters" },
      { label: "Cylinder Material", value: "Alloy Steel" },
      { label: "Working Pressure", value: "21 MPa" },
      { label: "Export Pressure", value: "0.65±0.2 MPa" },
      { label: "Breathing Resistance", value: "600 Pa (absolute value)" },
      { label: "Duration Time", value: "15 minutes" },
      { label: "Weight", value: "7 kg" },
    ],
    features: [
      "15 minutes of emergency breathing time",
      "Compact and lightweight at 7 kg",
      "Quick-donning protective hood",
      "Pressure gauge for monitoring",
      "Suitable for toxic and smoke environments",
      "Easy-to-use design for emergency situations",
      "Durable alloy steel cylinder",
      "SOLAS approved for marine applications",
    ],
    compliance: [
      "SOLAS 1974 (2000 Amendments)",
      "International Code for Fire Safety Systems",
      "IMO FSS Code",
      "Marine Equipment Directive (MED)",
    ],
  },
  scba: {
    id: "scba",
    name: "SCBA",
    category: "Fire Safety Equipment",
    certified: true,
    certificationText: "SOLAS & EN Approved",
    description:
      "Professional-grade self-contained breathing apparatus with 6L cylinder capacity providing 30 minutes of breathing time. Features advanced alarm system, pressure regulator, and respiratory protection for firefighting and rescue operations.",
    images: [
      "src/assets/7.png",
      // "src/assets/1.png",
      // "src/assets/2.png",
      // "src/assets/3.png",
    ],
    specifications: [
      { label: "Cylinder Capacity", value: "6 Liters" },
      { label: "Cylinder Material", value: "Alloy Steel" },
      { label: "Working Pressure", value: "0-30 MPa" },
      { label: "Output Pressure", value: "0.7±0.05 MPa" },
      { label: "Maximum Outflow", value: "450 L/min" },
      { label: "Service Time", value: "30 minutes" },
      { label: "Respiratory Resistance", value: "≤980 Pa" },
      { label: "Weight", value: "16 kg or more" },
      { label: "Package", value: "Plastic suitcase 728×440×300mm" },
    ],
    features: [
      "30 minutes of continuous breathing time",
      "6L high-capacity alloy steel cylinder",
      "Advanced alarm system (95 dB sound level)",
      "Pressure alarm at 5.5±0.5 MPa",
      "Safety valve opens at 1±1.2 MPa",
      "Flashing rate of 60 times/min",
      "Maximum outflow of 450 L/min",
      "Complete with plastic storage case",
      "Full face mask for complete protection",
    ],
    compliance: [
      "SOLAS 1974 as amended",
      "EN 137:2006",
      "ISO 23269-2:2011",
      "GB 16556-2007",
      "ISO 23269-3:2011",
      "MED 3.7",
      "MED 7.1",
    ],
  },
};
